### ISSUE TITLE
Clone at specific revision?

### ISSUE THREAD

**Issue by ashleydavies** [first-aml/git-clone-buildkite-plugin#1]
Hi, would you be open to a pull request to allow this plugin to clone a repository and optionally check it out at a specific revision?

Example expected usage:

```
- label: Some command
    plugins:
      - first-aml/git-clone:
          repository: git@github.com:first-aml/git-clone-buildkite-plugin.git
          revision: <git hash / tag / ...>
```

Intended semantics would be to do exactly the same if `revision` was not provided, and checkout the revision if it is. Probably something like:

```
if [[ -n "${ < revision variable > }" ]]; then
  cd <repository>
  git checkout "${< revision variable >}"
fi
```

Totally understood if you want to keep this minimal so I thought I'd ask before sending something up :)
